apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: carmel
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: https
    service.beta.kubernetes.io/linode-loadbalancer-port-443: '{ "tls-secret-name": "ssl", "protocol": "https" }'
spec:
  selector:
    app: carmel
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9080
  type: LoadBalancer