export default ({
  title1: 'Hey there, ',
  title2: 'Web3 Innovators',
  cards: [
    {
      cardNumberTestId: 'card-1-test-id',
      icon: '/images/icons/filled-shield.svg',
      iconAlt: '',
      iconTestId: 'shield-test-id',
      cardTextTestId: 'card-1-text-test-id',
      text1: 'Account',
      keyword1: 'Create Your FREE',
      text2: 'Establish',
      keyword2: ' a City',
      description:
        'Choose a username and sign up with your face or fingerprint. No passwords, no private keys.',
      buttonText: 'Buy Shields',
      buttonTestId: 'buy-shields-button',
    },
    {
      cardNumberTestId: 'card-2-test-id',
      icon: '/images/home/polygon.svg',
      iconAlt: '',
      iconTestId: 'polygon-test-id',
      cardTextTestId: 'card-2-text-test-id',
      text1: 'Funds',
      keyword1: 'Top up your account with',
      text2: 'Create',
      keyword2: ' Properties',
      description: 'Get your own topup link with your very own QR code. Just scan and transfer funds.',
      buttonText: 'Buy Land',
      buttonTestId: 'buy-land-button',
    },
    {
      cardNumberTestId: 'card-3-test-id',
      icon: '/images/icons/diamond.svg',
      iconAlt: '',
      iconTestId: 'diamond-test-id',
      cardTextTestId: 'card-3-text-test-id',
      text1: 'Assets',
      keyword1: 'Buy, sell, use',
      text2: 'Fund',
      keyword2: ' Quests',
      description: 'Browse the store to buy and sell digital assets. Or to use them inside Carmel Apps.',
      buttonText: 'Buy Gems',
      buttonTestId: 'buy-gems-button',
    },
  ],
})