export const FOOTER_TEXTS = {
  LOGO_FOOTER_ALT: 'logo footer',
  FUTURE_TEXT: 'Everyone An Innovator.',
  STORIES_LETTER_TEXT: 'Join "The Carmel Way"',
  COPYRIGHT_1: 'Carmel is a',
  COPYRIGHT_2: ' Fluid Trends ',
  COPYRIGHT_3: 'Web3 Product',
  MENU: {
    TITLE: 'Learn more:',
    TITLE2: 'Get involved:',
    TEXT_1: 'Product Story',
    TEXT_2: 'Economics',
    TEXT_3: 'Source Code',
    TEXT_4: 'Discord',
    TEXT_5: 'Telegram',
    TEXT_6: 'Twitter',
    LINK_1: 'https://carmel.io/docs/CarmelStory.pdf',
    LINK_2: 'https://carmel.io/docs/CarmelEconomics.pdf',
    LINK_3: 'https://github.com/fluidtrends/carmel',
    LINK_4: 'https://discord.com/invite/8EEdfFRS2U',
    LINK_5: 'https://t.me/carmelplatform',
    LINK_6: 'https://twitter.com/carmelprotocol',
  },
};
