export { default as login } from './login.web'
export { default as register } from './register.web'
export { default as reset } from './reset.web'
export { default as account } from './account.web'
export { default as logout } from './logout.web'
