export { default as main } from './main.web'
export { default as person } from './person.web'
export { default as team } from './team.web'
export { default as roadmap } from './roadmap.web'
export { default as terms } from './terms.web'
