export const CITIZEN_REGISTER_TEXT = {
  DETAILS: 'Details',
  CARMEL_USERNAME: 'Carmel Username',
  ETH_ADRESS: 'ETH Adress',
  EMAIL: 'Email',
  PLAN: 'Plan',
  SELECTED_PLAN: 'Selected Plan',
  CARMEL_CITIZEN: 'Carmel Citizen',
  DURATION: 'Duration',
  LIFETIME: 'Lifetime',
  TOTAL: 'Total',
  TO_PAY: 'To Pay Now',
  MONEY: 'Free',
  BUTTON: 'Proceed to Checkout',
};
