export const REGISTER_TEXT = {
  TITLE_1: 'Join the Carmel',
  TITLE_2: 'Waiting List',
  TITLE_MOBILE_1: 'Join the',
  TITLE_MOBILE_2: 'Carmel',
  TITLE_MOBILE_3: 'Waiting List',
  TITLE_IMG_ALT: 'Carmel Membership Card',
  SEE_BELOW_TEXT: 'Lifetime Membership Cards Are Coming Soon!',
  GENERAL: 'General Details',
  USENARME_ALT: 'useranme',
  USERNAME_IMAGE_SRC: 'images/icons/register/username-icon.svg',
  ETHERUM_ALT: 'etherum',
  ETHERUM_IMAGE_SRC: 'images/icons/register/etherum-icon.svg',
  MAIL_ALT: 'mail',
  MAIL_IMAGE_SRC: 'images/icons/register/mail-icon.svg',
  SELECT_PLAN: 'Select your Plan',
  CITIZEN: 'CITIZEN',
  FREE: 'Free',
  FOREVER_FREE: 'Forever Free',
  REZIDENT: 'REZIDENT',
  ONE_TIME_PAYMENT: 'One time payment',
  REZIDENT_VALUE: '750$',
  AMBASSADOR_INPUT: 'ambassador-input',
  AMBASSADOR: 'AMBASSADOR',
  AMBASSADOR_VALUE: '1450$',
};
