const NEW_QUEST_SCREEN_TEXT = {
  TITLE: 'ADD A NEW QUEST',
  BACK_BUTTON_TEXT: '< back to ',
  QUEST_TITLE_INPUT: 'Title',
  QUEST_DESCRIPTION_INPUT: 'Description',
  POST_COMMENT_BUTTON: 'Post',
  CANCEL_COMMENT_BUTTON: 'Cancel',
};

export default NEW_QUEST_SCREEN_TEXT;
