export { default as Register } from './register'
export { default as ResetPassword } from './reset'
export { default as Level } from './level'
export { default as Login } from './login'
export { default as Home } from './home'
