export { default as Register } from './register'
export { default as ResetPassword } from './reset'
export { default as Level } from './level'
export { default as Profile } from './profile'
export { default as Login } from './login'
export { default as Referrals } from './referrals'
export { default as Home } from './home'
